name: Build Desktop Extension

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  release:
    types: [published]

jobs:
  build-dxt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Install DXT CLI
        run: npm install -g @anthropic-ai/dxt

      - name: Build DXT package
        run: npx @anthropic-ai/dxt pack

      - name: Get package info
        id: package
        run: |
          echo "name=$(node -p "require('./package.json').name")" >> $GITHUB_OUTPUT
          echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Upload DXT artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.package.outputs.name }}-${{ steps.package.outputs.version }}.dxt
          path: "*.dxt"
          retention-days: 90

      - name: Upload DXT to release (if release)
        if: github.event_name == 'release'
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./${{ steps.package.outputs.name }}.dxt
          asset_name: ${{ steps.package.outputs.name }}-${{ steps.package.outputs.version }}.dxt
          asset_content_type: application/zip